import assert from 'node:assert/strict'
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync, existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { test } from 'vitest'

import {
  STAMP_SUFFIX,
  isInstallable,
  stampExisting,
  stampPathFor,
} from './write-artifact-stamp.mjs'

test('only the files a customer downloads get stamped', () => {
  for (const name of [
    'Hermes-9.9.9-win-x64.exe',
    'Hermes-9.9.9-mac-arm64.dmg',
    'Hermes-9.9.9-linux-x86_64.AppImage',
    'Hermes-9.9.9-linux-amd64.deb',
    'Hermes-9.9.9-win-x64.msi',
  ]) {
    assert.equal(isInstallable(name), true, name)
  }

  // The by-products electron-builder leaves in release/. A .blockmap in
  // particular would otherwise produce a sidecar that reads like a second
  // Windows build.
  for (const name of [
    'Hermes-9.9.9-win-x64.exe.blockmap',
    'latest.yml',
    'latest-mac.yml',
    'builder-debug.yml',
    'linux-unpacked',
  ]) {
    assert.equal(isInstallable(name), false, name)
  }
})

test('the sidecar sits next to the artifact under a fixed suffix', () => {
  assert.equal(
    stampPathFor('/release/Hermes-9.9.9-win-x64.exe'),
    '/release/Hermes-9.9.9-win-x64.exe' + STAMP_SUFFIX,
  )
})

test('stampExisting refuses to invent a commit', () => {
  for (const commit of [undefined, '', 'HEAD', 'not-a-sha', 'zzzzzzz']) {
    assert.throws(() => stampExisting(['/release/a.dmg'], { commit }), /requires the full commit/)
  }
})

test('stampExisting writes a stamp the collector can read', () => {
  const dir = mkdtempSync(path.join(tmpdir(), 'artifact-stamp-'))
  try {
    const artifact = path.join(dir, 'Hermes-9.9.9-mac-arm64.dmg')
    writeFileSync(artifact, 'not really a disk image')

    const written = stampExisting([artifact], {
      commit: 'c'.repeat(40),
      branch: 'main',
      builtAt: '2026-08-11T00:00:00.000Z',
    })

    assert.deepEqual(written, [artifact + STAMP_SUFFIX])
    assert.deepEqual(JSON.parse(readFileSync(written[0], 'utf8')), {
      schemaVersion: 1,
      commit: 'c'.repeat(40),
      branch: 'main',
      builtAt: '2026-08-11T00:00:00.000Z',
      dirty: false,
      source: 'manual',
    })
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
})

test('packaging a tree that was never built fails loudly', async () => {
  // The hook resolves build/install-stamp.json relative to its own directory,
  // so this exercises the real repository: the file is generated by `npm run
  // build` and is not committed. Whichever state the checkout is in, the
  // contract is the same — a stamp, or an error naming the missing file.
  const { default: afterAllArtifactBuild } = await import('./write-artifact-stamp.mjs')
  const dir = mkdtempSync(path.join(tmpdir(), 'artifact-stamp-hook-'))
  try {
    const artifact = path.join(dir, 'Hermes-9.9.9-linux-x86_64.AppImage')
    writeFileSync(artifact, 'not really an AppImage')

    const stampFile = path.resolve(import.meta.dirname, '..', 'build', 'install-stamp.json')
    if (existsSync(stampFile)) {
      const written = await afterAllArtifactBuild({ artifactPaths: [artifact] })
      assert.deepEqual(written, [artifact + STAMP_SUFFIX])
      assert.deepEqual(
        JSON.parse(readFileSync(written[0], 'utf8')),
        JSON.parse(readFileSync(stampFile, 'utf8')),
      )
    } else {
      await assert.rejects(
        afterAllArtifactBuild({ artifactPaths: [artifact] }),
        /install-stamp\.json is missing/,
      )
    }
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
})

test('a build that produced no installable artifact is not an error', async () => {
  const { default: afterAllArtifactBuild } = await import('./write-artifact-stamp.mjs')
  assert.deepEqual(await afterAllArtifactBuild({ artifactPaths: ['latest.yml'] }), [])
  assert.deepEqual(await afterAllArtifactBuild({}), [])
})

test('a half-written stamp is caught here, not on the server', async () => {
  // Import a copy pointed at a scratch tree, so the real build/ directory is
  // untouched: this test must never depend on repository state it can damage.
  const dir = mkdtempSync(path.join(tmpdir(), 'artifact-stamp-bad-'))
  try {
    const scripts = path.join(dir, 'scripts')
    mkdirSync(scripts, { recursive: true })
    mkdirSync(path.join(dir, 'build'), { recursive: true })
    writeFileSync(path.join(dir, 'build', 'install-stamp.json'), '{"schemaVersion":1,"comm')
    for (const name of ['write-artifact-stamp.mjs', 'utils.mjs']) {
      writeFileSync(
        path.join(scripts, name),
        readFileSync(path.resolve(import.meta.dirname, name), 'utf8'),
      )
    }

    const artifact = path.join(dir, 'Hermes-9.9.9-win-x64.exe')
    writeFileSync(artifact, 'not really an installer')

    const mod = await import(path.join(scripts, 'write-artifact-stamp.mjs'))
    await assert.rejects(mod.default({ artifactPaths: [artifact] }), SyntaxError)
    assert.equal(existsSync(artifact + STAMP_SUFFIX), false)
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
})
